version: '3.8'

services:
  api:
    build: ./api
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    build: ./db
    restart: always
    ports:
      - 3306:3306

  front:
    build: ./front
    ports:
      - 3000:3000
    depends_on:
      - api
