version: '3.8'

services:

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - 3306:3306
    env_file:
      .env
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  api:
    build: ./api
    container_name: api
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      .env

  front:
    build: ./front
    ports:
      - 3000:3000
    depends_on:
      - api
